# version: '2'
# networks:
#   bridge:
#     driver: bridge
services:
  web:
    image: "xwiki:17.9-mariadb-tomcat"
    container_name: xwiki
    depends_on:
      - db
    ports:
      - "8380:8080"
    environment:
    - DB_USER=${DB_USER}
    - DB_PASSWORD=${DB_PASSWORD}

    # Can be either service name or container name.
    # Docker Compose sets up an internal DNS that allows containers to find each other using:
    # - The service name (db)
    # - The container name (xwiki-mariadb-db)
    - DB_HOST=db
    volumes:
      - xwiki-data:/usr/local/xwiki
      # - ./xwiki.properties:/usr/local/xwiki/xwiki.properties:ro
      # - ./xwiki.cfg:/usr/local/xwiki/xwiki.cfg:ro
      # - ./hibernate.cfg.xml:/usr/local/xwiki/hibernate.cfg.xml:ro  
    # networks:
    #   - bridge
  db:
    image: "mariadb:11.6"
    container_name: xwiki-db
    volumes:
      - mariadb-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=xwiki      
    command:
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_bin"
      - "--explicit-defaults-for-timestamp=1"
    # networks:
    #   - bridge
volumes:
  mariadb-data: 
  xwiki-data: 