# networks:
#   internal-net:
#     driver: bridge

volumes:
  nginx-proxy-manager_data:
  nginx-proxy-manager_letsencrypt:

services:
  cloudflare-tunnel:
    image: cloudflare/cloudflared:2025.10.0
    container_name: cloudflared-tunnel
    restart: unless-stopped
    environment:
      - TUNNEL_NAME=bitrealm-cloudflare-tunnel
      - TUNNEL_TOKEN=$TUNNEL_TOKEN
    volumes:
      - ./config:/etc/cloudflared
    command: tunnel --no-autoupdate run
    # networks:
    #   - internal-net
    depends_on:
      - nginx-proxy-manager

  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:2.12.6'
    container_name: nginx-proxy-manager
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
      - '81:81'
    volumes:
      - nginx-proxy-manager_data:/data
      - nginx-proxy-manager_letsencrypt:/etc/letsencrypt
